// packages/cli/templates/vue/src/App.vue
<script setup lang="ts">
import { AI } from '@nearstack-dev/ai';
import { computed, onMounted, ref } from 'vue';
import { NoteModel, type Note } from './models/Note';
import TheSidebar from './components/TheSidebar.vue';
import NoteEditor from './components/NoteEditor.vue';
import AIPanel from './components/AIPanel.vue';

const ai = new AI();
const notes = ref<Note[]>([]);
const activeNoteId = ref<string | null>(null);
const search = ref('');
const showAI = ref(false);

const filteredNotes = computed(() =>
  notes.value
    .filter(note => {
      if (!search.value) return true;
      const q = search.value.toLowerCase();
      return (
        note.title.toLowerCase().includes(q) ||
        note.content.toLowerCase().includes(q) ||
        note.tags.some(t => t.toLowerCase().includes(q))
      );
    })
    .sort((a, b) => {
      if (a.pinned !== b.pinned) return a.pinned ? -1 : 1;
      return b.updatedAt - a.updatedAt;
    }),
);

const activeNote = computed(() => notes.value.find(n => n.id === activeNoteId.value) ?? null);
const allTags = computed(() => [...new Set(notes.value.flatMap(n => n.tags))]);

async function refreshNotes() {
  notes.value = await NoteModel.table().getAll();
}

async function createNote() {
  const note = await NoteModel.table().insert({
    title: '',
    content: '',
    tags: [],
    pinned: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  });
  activeNoteId.value = note.id;
  await refreshNotes();
}

function handleExport() {
  const blob = new Blob([JSON.stringify(notes.value, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'nearstack-notes.json';
  a.click();
  URL.revokeObjectURL(url);
}

function handleImport() {
  const input = document.createElement('input');
  input.type = 'file';
  input.accept = '.json';
  input.onchange = async (e) => {
    const file = (e.target as HTMLInputElement).files?.[0];
    if (!file) return;
    const text = await file.text();
    const imported = JSON.parse(text) as Note[];
    for (const note of imported) {
      const { id, ...data } = note;
      await NoteModel.table().insert(data);
    }
    await refreshNotes();
  };
  input.click();
}

onMounted(async () => {
  await refreshNotes();
  NoteModel.subscribe(() => void refreshNotes());
  await ai.ready();
});
</script>

<template>
  <div class="flex h-screen flex-col bg-white text-black">
    <header class="flex items-center justify-between border-b border-neutral-200 px-6 py-3">
      <div class="flex items-center gap-3">
        <div class="h-3.5 w-3.5 bg-black" />
        <h1 class="text-base font-semibold tracking-tight">Nearstack Notes</h1>
      </div>
      <div class="flex items-center gap-1.5">
        <button
          @click="showAI = !showAI"
          :class="[
            'px-3 py-1.5 text-sm font-medium transition-colors',
            showAI ? 'bg-black text-white' : 'border border-neutral-300 hover:bg-neutral-100',
          ]"
        >
          AI Assistant
        </button>
        <button @click="handleExport" class="border border-neutral-300 px-3 py-1.5 text-sm hover:bg-neutral-100">
          Export
        </button>
        <button @click="handleImport" class="border border-neutral-300 px-3 py-1.5 text-sm hover:bg-neutral-100">
          Import
        </button>
      </div>
    </header>

    <div class="flex flex-1 overflow-hidden">
      <TheSidebar
        :notes="filteredNotes"
        :active-note-id="activeNoteId"
        :search="search"
        @update:search="search = $event"
        @select-note="activeNoteId = $event"
        @new-note="createNote"
      />

      <main class="flex flex-1 flex-col overflow-hidden">
        <NoteEditor v-if="activeNote" :note="activeNote" />
        <div v-else class="flex flex-1 items-center justify-center">
          <div class="text-center text-neutral-400">
            <p class="text-lg font-light">Select a note or create a new one</p>
            <button @click="createNote" class="mt-4 bg-black px-4 py-2 text-sm text-white hover:bg-neutral-800">
              New Note
            </button>
          </div>
        </div>
      </main>

      <aside v-if="showAI" class="w-96 border-l border-neutral-200">
        <AIPanel :notes="notes" :ai="ai" />
      </aside>
    </div>

    <footer class="border-t border-neutral-200 px-6 py-2 text-[11px] text-neutral-400">
      {{ notes.length }} {{ notes.length === 1 ? 'note' : 'notes' }} &middot;
      {{ allTags.length }} {{ allTags.length === 1 ? 'tag' : 'tags' }} &middot;
      Stored locally in your browser
    </footer>
  </div>
</template>

// packages/cli/templates/angular/src/app/app.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { AI, Message, ModelInfo } from '@nearstack-dev/ai';
import { Note, NoteModel } from './models/note.model';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './app.component.html',
})
export class AppComponent implements OnInit {
  private readonly ai = new AI();
  private saveTimer: ReturnType<typeof setTimeout> | null = null;

  notes: Note[] = [];
  activeNoteId: string | null = null;
  search = '';
  showAI = false;

  // Editor state
  editorTitle = '';
  editorContent = '';
  tagInput = '';

  // AI state
  models: ModelInfo[] = [];
  selectedModel = '';
  isDownloading = false;
  downloadProgress = 0;
  messages: Message[] = [];
  chatInput = '';
  isSending = false;
  error = '';

  get filteredNotes(): Note[] {
    return this.notes
      .filter(note => {
        if (!this.search) return true;
        const q = this.search.toLowerCase();
        return (
          note.title.toLowerCase().includes(q) ||
          note.content.toLowerCase().includes(q) ||
          note.tags.some(t => t.toLowerCase().includes(q))
        );
      })
      .sort((a, b) => {
        if (a.pinned !== b.pinned) return a.pinned ? -1 : 1;
        return b.updatedAt - a.updatedAt;
      });
  }

  get activeNote(): Note | null {
    return this.notes.find(n => n.id === this.activeNoteId) ?? null;
  }

  get pinnedNotes(): Note[] {
    return this.filteredNotes.filter(n => n.pinned);
  }

  get unpinnedNotes(): Note[] {
    return this.filteredNotes.filter(n => !n.pinned);
  }

  get allTags(): string[] {
    return [...new Set(this.notes.flatMap(n => n.tags))];
  }

  get wordCount(): number {
    return this.editorContent.trim() ? this.editorContent.trim().split(/\s+/).length : 0;
  }

  get needsSetup(): boolean {
    const m = this.models.find(m => m.id === this.selectedModel);
    return !m || (m.status.state !== 'cached' && m.status.state !== 'ready');
  }

  get selectedModelInfo(): ModelInfo | undefined {
    return this.models.find(m => m.id === this.selectedModel);
  }

  async ngOnInit() {
    await this.refreshNotes();
    NoteModel.subscribe(() => void this.refreshNotes());
    await this.ai.ready();
    this.models = this.ai.models.list();
    this.selectedModel = this.ai.models.active()?.id ?? '';
  }

  async refreshNotes() {
    this.notes = await NoteModel.table().getAll();
    if (this.activeNote) {
      this.editorTitle = this.activeNote.title;
      this.editorContent = this.activeNote.content;
    }
  }

  selectNote(id: string) {
    this.activeNoteId = id;
    const note = this.notes.find(n => n.id === id);
    if (note) {
      this.editorTitle = note.title;
      this.editorContent = note.content;
    }
  }

  async createNote() {
    const note = await NoteModel.table().insert({
      title: '',
      content: '',
      tags: [],
      pinned: false,
      createdAt: Date.now(),
      updatedAt: Date.now(),
    });
    this.activeNoteId = note.id;
    this.editorTitle = '';
    this.editorContent = '';
  }

  private save(updates: Partial<Note>) {
    if (!this.activeNoteId) return;
    if (this.saveTimer) clearTimeout(this.saveTimer);
    const id = this.activeNoteId;
    this.saveTimer = setTimeout(() => {
      void NoteModel.table().update(id, { ...updates, updatedAt: Date.now() });
    }, 300);
  }

  onTitleChange(value: string) {
    this.editorTitle = value;
    this.save({ title: value });
  }

  onContentChange(value: string) {
    this.editorContent = value;
    this.save({ content: value });
  }

  addTag() {
    const tag = this.tagInput.trim().toLowerCase();
    if (!tag || !this.activeNote || this.activeNote.tags.includes(tag)) {
      this.tagInput = '';
      return;
    }
    void NoteModel.table().update(this.activeNote.id, {
      tags: [...this.activeNote.tags, tag],
      updatedAt: Date.now(),
    });
    this.tagInput = '';
  }

  removeTag(tag: string) {
    if (!this.activeNote) return;
    void NoteModel.table().update(this.activeNote.id, {
      tags: this.activeNote.tags.filter(t => t !== tag),
      updatedAt: Date.now(),
    });
  }

  togglePin() {
    if (!this.activeNote) return;
    void NoteModel.table().update(this.activeNote.id, {
      pinned: !this.activeNote.pinned,
      updatedAt: Date.now(),
    });
  }

  deleteNote() {
    if (!this.activeNote) return;
    void NoteModel.table().delete(this.activeNote.id);
    this.activeNoteId = null;
  }

  handleExport() {
    const blob = new Blob([JSON.stringify(this.notes, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'nearstack-notes.json';
    a.click();
    URL.revokeObjectURL(url);
  }

  handleImport() {
    const input = document.createElement('input');
    input.type = 'file';
    input.accept = '.json';
    input.onchange = async (e) => {
      const file = (e.target as HTMLInputElement).files?.[0];
      if (!file) return;
      const text = await file.text();
      const imported = JSON.parse(text) as Note[];
      for (const note of imported) {
        const { id, ...data } = note;
        await NoteModel.table().insert(data);
      }
    };
    input.click();
  }

  private buildSystemPrompt(): string | undefined {
    if (this.notes.length === 0) return undefined;
    const summary = this.notes
      .sort((a, b) => b.updatedAt - a.updatedAt)
      .slice(0, 20)
      .map(n => {
        const tags = n.tags.length ? ` [${n.tags.join(', ')}]` : '';
        return `- "${n.title || 'Untitled'}"${tags}: ${n.content.slice(0, 200)}`;
      })
      .join('\n');
    return [
      'You are a helpful AI assistant in a personal notes app.',
      `The user has ${this.notes.length} notes:`,
      summary,
      'Be concise. Reference note titles when relevant.',
    ].join('\n\n');
  }

  async onModelSelect(modelId: string) {
    this.selectedModel = modelId;
    const model = this.models.find(m => m.id === modelId);
    if (!model) return;

    if (model.status.state === 'available') {
      this.isDownloading = true;
      this.downloadProgress = 0;
      const unsub = this.ai.subscribe(state => {
        if (state.downloading?.modelId === modelId) {
          this.downloadProgress = state.downloading.progress;
        }
      });
      try {
        await this.ai.models.download(modelId);
      } finally {
        unsub();
        this.isDownloading = false;
      }
    }
    await this.ai.models.use(modelId);
    this.models = this.ai.models.list();
  }

  async sendMessage() {
    const text = this.chatInput.trim();
    if (!text) return;
    this.chatInput = '';
    this.error = '';
    const next: Message[] = [...this.messages, { role: 'user', content: text }];
    this.messages = next;
    this.isSending = true;
    try {
      const systemPrompt = this.buildSystemPrompt();
      const apiMessages: Message[] = systemPrompt
        ? [{ role: 'system', content: systemPrompt }, ...next]
        : next;
      const reply = await this.ai.chat(apiMessages);
      this.messages = [...next, { role: 'assistant', content: reply }];
    } catch (e) {
      this.error = e instanceof Error ? e.message : 'Chat failed';
    } finally {
      this.isSending = false;
    }
  }

  clearChat() {
    this.messages = [];
    this.error = '';
  }

  formatDate(timestamp: number): string {
    const diff = Date.now() - timestamp;
    if (diff < 60000) return 'Just now';
    if (diff < 3600000) return `${Math.floor(diff / 60000)}m ago`;
    if (diff < 86400000) return `${Math.floor(diff / 3600000)}h ago`;
    if (diff < 604800000) return `${Math.floor(diff / 86400000)}d ago`;
    return new Date(timestamp).toLocaleDateString();
  }
}

<div class="flex h-screen flex-col bg-white text-black">
  <!-- Header -->
  <header class="flex items-center justify-between border-b border-neutral-200 px-6 py-3">
    <div class="flex items-center gap-3">
      <div class="h-3.5 w-3.5 bg-black"></div>
      <h1 class="text-base font-semibold tracking-tight">Nearstack Notes</h1>
    </div>
    <div class="flex items-center gap-1.5">
      <button
        (click)="showAI = !showAI"
        [class]="'px-3 py-1.5 text-sm font-medium transition-colors ' + (showAI ? 'bg-black text-white' : 'border border-neutral-300 hover:bg-neutral-100')"
      >
        AI Assistant
      </button>
      <button (click)="handleExport()" class="border border-neutral-300 px-3 py-1.5 text-sm hover:bg-neutral-100">Export</button>
      <button (click)="handleImport()" class="border border-neutral-300 px-3 py-1.5 text-sm hover:bg-neutral-100">Import</button>
    </div>
  </header>

  <!-- Main layout -->
  <div class="flex flex-1 overflow-hidden">
    <!-- Sidebar -->
    <aside class="flex w-72 flex-col border-r border-neutral-200 bg-neutral-50">
      <div class="space-y-2 p-3">
        <input
          type="text"
          [(ngModel)]="search"
          name="search"
          placeholder="Search notes..."
          class="w-full border border-neutral-300 bg-white px-3 py-2 text-sm placeholder:text-neutral-400 focus:border-black focus:outline-none"
        />
        <button (click)="createNote()" class="w-full bg-black px-3 py-2 text-sm font-medium text-white hover:bg-neutral-800">+ New Note</button>
      </div>
      <div class="flex-1 overflow-y-auto">
        <p *ngIf="pinnedNotes.length > 0" class="px-3 pb-1 pt-3 text-[11px] font-semibold uppercase tracking-widest text-neutral-400">Pinned</p>
        <button
          *ngFor="let note of pinnedNotes"
          (click)="selectNote(note.id)"
          [class]="'w-full px-3 py-2.5 text-left transition-colors ' + (note.id === activeNoteId ? 'bg-black text-white' : 'hover:bg-neutral-100')"
        >
          <p [class]="'truncate text-sm font-medium ' + (note.id === activeNoteId ? 'text-white' : 'text-black')">{{ note.title || 'Untitled' }}</p>
          <p [class]="'mt-0.5 truncate text-xs ' + (note.id === activeNoteId ? 'text-neutral-300' : 'text-neutral-500')">{{ note.content.slice(0, 80) || 'Empty note' }}</p>
          <span class="mt-1 text-[11px] text-neutral-400">{{ formatDate(note.updatedAt) }}</span>
        </button>

        <p *ngIf="pinnedNotes.length > 0 && unpinnedNotes.length > 0" class="px-3 pb-1 pt-3 text-[11px] font-semibold uppercase tracking-widest text-neutral-400">All Notes</p>
        <button
          *ngFor="let note of unpinnedNotes"
          (click)="selectNote(note.id)"
          [class]="'w-full px-3 py-2.5 text-left transition-colors ' + (note.id === activeNoteId ? 'bg-black text-white' : 'hover:bg-neutral-100')"
        >
          <p [class]="'truncate text-sm font-medium ' + (note.id === activeNoteId ? 'text-white' : 'text-black')">{{ note.title || 'Untitled' }}</p>
          <p [class]="'mt-0.5 truncate text-xs ' + (note.id === activeNoteId ? 'text-neutral-300' : 'text-neutral-500')">{{ note.content.slice(0, 80) || 'Empty note' }}</p>
          <span class="mt-1 text-[11px] text-neutral-400">{{ formatDate(note.updatedAt) }}</span>
        </button>

        <p *ngIf="filteredNotes.length === 0" class="px-3 py-8 text-center text-sm text-neutral-400">
          {{ search ? 'No notes match your search' : 'No notes yet' }}
        </p>
      </div>
    </aside>

    <!-- Editor -->
    <main class="flex flex-1 flex-col overflow-hidden">
      <ng-container *ngIf="activeNote; else emptyState">
        <!-- Toolbar -->
        <div class="flex items-center justify-between border-b border-neutral-200 px-6 py-2">
          <div class="flex items-center gap-3">
            <button
              (click)="togglePin()"
              [class]="'px-2 py-1 text-xs font-medium transition-colors ' + (activeNote.pinned ? 'bg-black text-white' : 'border border-neutral-300 text-neutral-600 hover:bg-neutral-100')"
            >
              {{ activeNote.pinned ? 'Pinned' : 'Pin' }}
            </button>
            <span class="text-xs text-neutral-400">{{ wordCount }} {{ wordCount === 1 ? 'word' : 'words' }} &middot; {{ editorContent.length }} chars</span>
          </div>
          <button (click)="deleteNote()" class="px-2 py-1 text-xs text-neutral-400 transition-colors hover:text-red-600">Delete</button>
        </div>

        <!-- Title + Content -->
        <div class="flex-1 overflow-y-auto px-6 py-4">
          <input
            type="text"
            [value]="editorTitle"
            (input)="onTitleChange($any($event.target).value)"
            placeholder="Note title"
            class="w-full border-0 p-0 text-2xl font-semibold tracking-tight placeholder:text-neutral-300 focus:outline-none focus:ring-0"
          />
          <textarea
            [value]="editorContent"
            (input)="onContentChange($any($event.target).value)"
            placeholder="Start writing..."
            class="mt-4 block min-h-[400px] w-full resize-none border-0 p-0 text-base leading-relaxed text-neutral-700 placeholder:text-neutral-300 focus:outline-none focus:ring-0"
          ></textarea>
        </div>

        <!-- Tags -->
        <div class="border-t border-neutral-200 px-6 py-3">
          <div class="flex flex-wrap items-center gap-2">
            <span *ngFor="let tag of activeNote.tags" class="inline-flex items-center gap-1 border border-neutral-200 px-2 py-0.5 text-xs">
              {{ tag }}
              <button (click)="removeTag(tag)" class="text-neutral-400 hover:text-black">&times;</button>
            </span>
            <form (ngSubmit)="addTag()" class="inline-flex">
              <input
                [(ngModel)]="tagInput"
                name="tagInput"
                type="text"
                placeholder="Add tag..."
                class="w-24 border-0 p-0 text-xs placeholder:text-neutral-400 focus:outline-none focus:ring-0"
              />
            </form>
          </div>
        </div>
      </ng-container>

      <ng-template #emptyState>
        <div class="flex flex-1 items-center justify-center">
          <div class="text-center text-neutral-400">
            <p class="text-lg font-light">Select a note or create a new one</p>
            <button (click)="createNote()" class="mt-4 bg-black px-4 py-2 text-sm text-white hover:bg-neutral-800">New Note</button>
          </div>
        </div>
      </ng-template>
    </main>

    <!-- AI Panel -->
    <aside *ngIf="showAI" class="flex w-96 flex-col border-l border-neutral-200">
      <div class="flex items-center justify-between border-b border-neutral-200 px-4 py-2">
        <h2 class="text-sm font-semibold">AI Assistant</h2>
        <button *ngIf="messages.length > 0" (click)="clearChat()" class="text-xs text-neutral-400 hover:text-black">Clear</button>
      </div>

      <!-- Setup -->
      <div *ngIf="needsSetup" class="flex flex-1 flex-col items-center justify-center p-6 text-center">
        <p class="text-sm font-medium">Set up a local AI model</p>
        <p class="mt-1 text-xs text-neutral-500">Models run entirely on your device. No data leaves your browser.</p>
        <select
          [ngModel]="selectedModel"
          (ngModelChange)="onModelSelect($event)"
          name="aiModel"
          class="mt-4 w-full border border-neutral-300 bg-white px-3 py-2 text-sm focus:border-black focus:outline-none"
          [disabled]="isDownloading"
        >
          <option value="">Select a model</option>
          <option *ngFor="let m of models" [value]="m.id">{{ m.provider }} &middot; {{ m.name }}</option>
        </select>
        <button
          *ngIf="selectedModelInfo?.status?.state === 'available'"
          (click)="onModelSelect(selectedModel)"
          class="mt-3 w-full bg-black px-3 py-2 text-sm text-white hover:bg-neutral-800"
        >
          Download model
        </button>
        <div *ngIf="isDownloading" class="mt-3 w-full">
          <div class="h-1 w-full overflow-hidden bg-neutral-200">
            <div class="h-full bg-black transition-all" [style.width.%]="downloadProgress * 100"></div>
          </div>
          <p class="mt-1 text-xs text-neutral-500">Downloading {{ (downloadProgress * 100) | number: '1.0-0' }}%</p>
        </div>
        <div *ngIf="selectedModelError" class="mt-3 w-full">
          <p class="text-xs text-red-600">{{ selectedModelError }}</p>
          <button
            (click)="onModelSelect(selectedModel)"
            [disabled]="isDownloading"
            class="mt-2 w-full bg-black px-3 py-2 text-sm text-white hover:bg-neutral-800 disabled:opacity-50"
          >
            Retry download
          </button>
        </div>
      </div>

      <!-- Chat -->
      <ng-container *ngIf="!needsSetup">
        <div class="flex-1 overflow-y-auto p-4">
          <div *ngIf="messages.length === 0" class="flex h-full items-center justify-center text-center text-neutral-400">
            <div>
              <p class="text-sm font-medium">Ask about your notes</p>
              <div class="mt-3 space-y-1.5 text-xs text-neutral-500">
                <p>&ldquo;Summarize my recent notes&rdquo;</p>
                <p>&ldquo;What topics come up most?&rdquo;</p>
                <p>&ldquo;Help me draft a note about...&rdquo;</p>
              </div>
            </div>
          </div>
          <div class="space-y-3">
            <div
              *ngFor="let msg of messages; index as i"
              [class]="'text-sm ' + (msg.role === 'assistant' ? 'text-neutral-700' : 'ml-8 bg-neutral-100 px-3 py-2')"
            >
              {{ msg.content }}
            </div>
            <p *ngIf="error" class="text-xs text-red-600">{{ error }}</p>
          </div>
        </div>
        <form (ngSubmit)="sendMessage()" class="border-t border-neutral-200 p-3">
          <div class="flex gap-2">
            <input
              [(ngModel)]="chatInput"
              name="chatInput"
              placeholder="Ask anything..."
              class="flex-1 border border-neutral-300 bg-white px-3 py-2 text-sm placeholder:text-neutral-400 focus:border-black focus:outline-none"
            />
            <button type="submit" [disabled]="isSending" class="bg-black px-3 py-2 text-sm text-white hover:bg-neutral-800 disabled:opacity-50">Send</button>
          </div>
        </form>
      </ng-container>
    </aside>
  </div>

  <!-- Footer -->
  <footer class="border-t border-neutral-200 px-6 py-2 text-[11px] text-neutral-400">
    {{ notes.length }} {{ notes.length === 1 ? 'note' : 'notes' }} &middot;
    {{ allTags.length }} {{ allTags.length === 1 ? 'tag' : 'tags' }} &middot;
    Stored locally in your browser
  </footer>
</div>
